data:
  train_dataset: /home/ktezoren/ffcv/beton-dsets/cifar10-lt-train.beton
  val_dataset: /home/ktezoren/ffcv/beton-dsets/cifar10-lt-test.beton
training:
  batch_size: 128
  epochs: 200
  lr: 0.1
  momentum: 0.9
  lr_peak_epoch: 5
  weight_decay: 2e-4
  lr_tta: false
  num_workers: 2
