data:
  gpu: 0
  num_workers: 8
  train_dataset: /home/ktezoren/ffcv/beton-dsets/cifar10_train.beton
  val_dataset: /home/ktezoren/ffcv/beton-dsets/cifar10_test.beton
training:
  batch_size: 128
  epochs: 200
  lr: 0.5
  momentum: 0.9
  lr_peak_epoch: 5
  momentum: 0.9
  weight_decay: 5e-4
  label_smoothing: 0.1
  lr_tta: true
  num_workers: 2
